apiVersion: "sparkoperator.k8s.io/v1beta2"
kind: SparkApplication
metadata:
  name: osds-spark-app
  namespace: spark-operator
spec:
  type: Python
  pythonVersion: "3"
  mode: cluster
  image: "osds-spark8s"
  mainApplicationFile: local:///opt/spark/work-dir/scripts/basic_spark.py
  sparkVersion: "3.5.0"
  restartPolicy:
    type: Never
  driver:
    coreLimit: "1"
    coreRequest: "1m"
    memory: "512m"
    labels:
      version: "3.5.0"
    serviceAccount: spark
  executor:
    coreLimit: "1"
    coreRequest: "1m"
    instances: 1
    memory: "512m"
    labels:
      version: "3.5.0"